name: Build Categraf for armv7

on:
  # 允许您在 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

# 在工作流级别定义环境变量
env:
  GO_VERSION: '1.24' # 采用和官方 ci.yml 一致的 Go 版本
  GOOS: linux
  GOARCH: arm
  GOARM: 7

jobs:
  build-for-armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Install libpcap dependency
        # 这是从官方 release.yml 中学到的关键步骤，用于编译网络插件
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Categraf Binary
        # Categraf 的项目结构比较简单，主程序在根目录
        # CGO_ENABLED=1 是必要的，因为它需要链接到我们刚刚安装的 libpcap C 库
        run: CGO_ENABLED=1 go build -ldflags="-s -w" -o categraf .

      - name: Prepare Artifact Package for Release
        # Categraf 的配置文件在 'conf' 目录下
        run: |
          mkdir -p package_root
          mv categraf package_root/
          cp -r conf package_root/
          tar -zcvf categraf-linux-armv7.tar.gz -C package_root .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: categraf-linux-armv7-package
          path: categraf-linux-armv7.tar.gz