name: Build Categraf for armv7 (Static)

on:
  # 允许您在 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

# 在工作流级别定义环境变量
env:
  GO_VERSION: '1.24'
  GOOS: linux
  GOARCH: arm
  GOARM: 7

jobs:
  build-for-armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Install ARM C Cross-Compiler and libpcap
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf libpcap-dev

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Statically-Linked Categraf Binary
        # 这是最终、最关键的修正：
        # -ldflags '... -extldflags "-static"' 指示Go的外部链接器（GCC）进行静态链接。
        # 这会将所有C库的依赖（包括libc和libpcap）都打包进最终的可执行文件中。
        env:
          CGO_ENABLED: 1
          CC: arm-linux-gnueabihf-gcc
        run: go build -ldflags='-s -w -extldflags "-static"' -o categraf .

      - name: Prepare Artifact Package for Release
        run: |
          mkdir -p package_root
          mv categraf package_root/
          cp -r conf package_root/
          tar -zcvf categraf-linux-armv7.tar.gz -C package_root .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: categraf-linux-armv7-package
          path: categraf-linux-armv7.tar.gz